// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Hk7FmL-qieUMFhVmQMQC19A_1mrZ3cA',
    appId: '1:324912269423:android:a73c8ad975951cbdd9e59a',
    messagingSenderId: '324912269423',
    projectId: 'agrobanco-sf-offline-001',
    storageBucket: 'agrobanco-sf-offline-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtXe8QmR8x2Y_L1qAJ3SQlfjt2vgMncX4',
    appId: '1:324912269423:ios:0e9a932943a01fa2d9e59a',
    messagingSenderId: '324912269423',
    projectId: 'agrobanco-sf-offline-001',
    storageBucket: 'agrobanco-sf-offline-001.firebasestorage.app',
    iosBundleId: 'com.agrobanco.salesforce.agrobancoSalesForce',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_6Cp-7wOtB_f2UynlEZAmVTaVTVlzsmY',
    appId: '1:324912269423:web:24da0eb2103c8926d9e59a',
    messagingSenderId: '324912269423',
    projectId: 'agrobanco-sf-offline-001',
    authDomain: 'agrobanco-sf-offline-001.firebaseapp.com',
    storageBucket: 'agrobanco-sf-offline-001.firebasestorage.app',
  );

}